### ISSUE TITLE
IndexOutOfBoundsException on CivTest

### ISSUE THREAD

**Issue by erocs** [Civcraft/RealisticBiomes#54]
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.rangeCheck(ArrayList.java:635) ~[?:1.7.0_79]
        at java.util.ArrayList.get(ArrayList.java:411) ~[?:1.7.0_79]
        at com.untamedears.realisticbiomes.listener.PlayerListener.onPlayerInteractEvent(PlayerListener.java:54) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 17 more
[12:32:18 ERROR]: Could not pass event PlayerInteractEvent to RealisticBiomes v0.6.5.0

**Comment by erocs** [comment]
Also

Caused by: java.lang.NullPointerException
        at com.untamedears.realisticbiomes.listener.PlayerListener.onPlayerInteractEvent(PlayerListener.java:59) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_79]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_79]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        ... 17 more

**Comment by gipsy-king** [comment]
https://github.com/Civcraft/RealisticBiomes/pull/53#discussion_r37060590

**Comment by ttk2** [comment]
I just figured it was losing db connection maybe this is related.
